version: "3.7"

services:
  email-capture:
    image: nginx:alpine
    volumes:
      - email_capture_data:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - RLnet
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.email-capture.rule=Host(`sites.rlucio.com`)
        - traefik.http.routers.email-capture.entrypoints=websecure
        - traefik.http.routers.email-capture.tls.certresolver=letsencryptresolver
        - traefik.http.services.email-capture.loadbalancer.server.port=80
        - traefik.http.services.email-capture.loadbalancer.passHostHeader=true

volumes:
  email_capture_data:
    external: true

networks:
  RLnet:
    external: true
