version: "3.7"

services:
  sites_diversos:
    build: .
    image: sites_diversos:latest
    networks:
      - RLnet
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.sites-diversos.rule=Host(`sites.rlucio.com`)
      - traefik.http.routers.sites-diversos.entrypoints=websecure
      - traefik.http.routers.sites-diversos.tls.certresolver=letsencryptresolver
      - traefik.http.services.sites-diversos.loadbalancer.server.port=80
      - traefik.http.services.sites-diversos.loadbalancer.passHostHeader=true

networks:
  RLnet:
    external: true
